name: FamousQuotes build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '25'

    - name: Build the project
      run: sh ./gradlew build

    - name: Generate the static site
      run: sh ./gradlew run

    - name: Setup Pages
      uses: actions/configure-pages@v6

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v5
      with:
        path: './dist/'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5